################################################################################
# WARNING: any updates made here should also be made to 'tests/.swiftlint'
################################################################################

excluded:
  - antlr4-master
  - .git
  - jokr/Antlr Generated Parser
  - example

  - tests/Unit Tests/Swift Translator Tests/TestAssignments
  - tests/Unit Tests/Swift Translator Tests/TestFunctionCalls
  - tests/Unit Tests/Swift Translator Tests/TestClassDeclarations
  - tests/Unit Tests/Swift Translator Tests/TestMethodCalls

  - tests/Acceptance Tests/Swift/TestAssignments
  - tests/Acceptance Tests/Swift/TestClasses
  - tests/Acceptance Tests/Swift/TestExpressions
  - tests/Acceptance Tests/Swift/TestFunctionCalls

disabled_rules:
  - todo
  - opening_brace
  - file_length

opt_in_rules:
  - force_unwrapping

line_length:
  - 80  # warning
  - 100 # error

identifier_name:
  min_length:
    error: 2
  excluded:
    - id

statement_position:
    statement_mode: uncuddled_else

